import Link from "next/link";
import { requireAuthenticatedUser } from "@/lib/supabase/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";

type Props = { searchParams: Promise<{ jobId?: string; ids?: string }> };

export default async function CandidateComparePage({ searchParams }: Props) {
  const user = await requireAuthenticatedUser();
  const { jobId, ids } = await searchParams;
  const candidateIds = (ids ?? "").split(",").filter(Boolean).slice(0, 5);
  if (!jobId || candidateIds.length < 2) return <main className="min-h-screen bg-bg px-4 pb-20 pt-24 sm:px-6 sm:pt-28 lg:px-8"><div className="mx-auto max-w-wrap"><Link href="/dashboard/agents/recruitos/candidates" className="mb-8 inline-flex min-h-10 items-center text-[13px] text-ink-dim">← Back to Candidates</Link><div className="rounded-xl border border-border p-7 sm:p-8"><h1 className="font-display text-xl font-semibold text-ink">Select candidates to compare</h1><p className="mt-3 text-sm text-ink-dim">Choose at least two candidates from a job pipeline.</p></div></div></main>;
  const { data: matches } = await supabaseAdmin.from("candidate_job_matches").select("id, candidate_id, match_score, recommendation, recruiter_status, latest_analysis_id, candidates ( id, full_name, email, headline, skills, years_experience )").eq("user_id", user.id).eq("job_id", jobId).in("candidate_id", candidateIds).order("match_score", { ascending: false, nullsFirst: false });
  const analysisIds = (matches ?? []).map((match) => match.latest_analysis_id).filter(Boolean) as string[];
  const { data: analyses } = analysisIds.length ? await supabaseAdmin.from("resume_analyses").select("id, matching_skills, missing_skills, potential_concerns, years_relevant_experience, summary").eq("user_id", user.id).in("id", analysisIds) : { data: [] };
  const analysisMap = new Map((analyses ?? []).map((analysis) => [analysis.id, analysis]));

  return <main className="min-h-screen bg-bg px-4 pb-20 pt-24 sm:px-6 sm:pt-28 lg:px-8"><div className="mx-auto max-w-wrap"><Link href={`/dashboard/agents/recruitos/jobs/${jobId}`} className="mb-8 inline-flex min-h-10 items-center text-[13px] text-ink-dim transition-colors hover:text-ink">← Back to Job</Link><div className="mb-9 border-b border-border pb-8 sm:mb-10 sm:pb-10"><p className="mb-4 font-mono text-[11px] tracking-[0.08em] text-accent">RECRUITOS / COMPARE</p><h1 className="font-display text-[clamp(36px,5vw,64px)] font-semibold leading-[1.05] text-ink">Compare candidates.</h1><p className="mt-4 max-w-[760px] text-[15px] leading-[1.7] text-ink-dim">Compare stored candidate and job-match intelligence side by side. RecruitOS assists the recruiter; it does not make the hiring decision.</p></div><div className="overflow-x-auto rounded-xl border border-border"><div className="min-w-[720px] grid" style={{ gridTemplateColumns: `180px repeat(${Math.max(matches?.length ?? 1, 1)}, minmax(220px, 1fr))` }}><div className="border-b border-border bg-surface/[0.35] p-5 font-mono text-[10px] uppercase tracking-[0.08em] text-ink-dim">Candidate</div>{matches?.map((match) => { const candidate = Array.isArray(match.candidates) ? match.candidates[0] : match.candidates; return <div key={match.id} className="border-b border-l border-border bg-surface/[0.18] p-5"><p className="font-display text-lg font-semibold text-ink">{candidate?.full_name || candidate?.email || "Unnamed"}</p><p className="mt-1 text-xs text-ink-dim">{candidate?.headline || "Candidate"}</p></div> })}
<div className="border-b border-border p-5 text-xs text-ink-dim">Match score</div>{matches?.map((match) => <div key={`score-${match.id}`} className="border-b border-l border-border p-5 font-display text-3xl font-semibold text-ink">{match.match_score ?? "—"}</div>)}
<div className="border-b border-border p-5 text-xs text-ink-dim">Recommendation</div>{matches?.map((match) => <div key={`rec-${match.id}`} className="border-b border-l border-border p-5 text-sm capitalize text-ink">{match.recommendation ?? "pending"}</div>)}
<div className="border-b border-border p-5 text-xs text-ink-dim">Pipeline</div>{matches?.map((match) => <div key={`status-${match.id}`} className="border-b border-l border-border p-5 text-sm capitalize text-ink">{match.recruiter_status}</div>)}
<div className="border-b border-border p-5 text-xs text-ink-dim">Experience</div>{matches?.map((match) => { const candidate = Array.isArray(match.candidates) ? match.candidates[0] : match.candidates; const analysis = match.latest_analysis_id ? analysisMap.get(match.latest_analysis_id) : null; return <div key={`exp-${match.id}`} className="border-b border-l border-border p-5 text-sm text-ink">{analysis?.years_relevant_experience ?? candidate?.years_experience ?? "Not available"} years</div> })}
<div className="border-b border-border p-5 text-xs text-ink-dim">Skills</div>{matches?.map((match) => { const candidate = Array.isArray(match.candidates) ? match.candidates[0] : match.candidates; const skills = Array.isArray(candidate?.skills) ? candidate.skills : []; return <div key={`skills-${match.id}`} className="border-b border-l border-border p-5"><div className="flex flex-wrap gap-2">{skills.slice(0, 10).map((skill) => <span key={String(skill)} className="rounded-md border border-border px-2 py-1 text-xs text-ink">{String(skill)}</span>)}</div></div> })}
<div className="border-b border-border p-5 text-xs text-ink-dim">Missing skills</div>{matches?.map((match) => { const analysis = match.latest_analysis_id ? analysisMap.get(match.latest_analysis_id) : null; return <div key={`missing-${match.id}`} className="border-b border-l border-border p-5 text-sm leading-[1.7] text-ink-dim">{(analysis?.missing_skills as string[] | undefined)?.join(", ") || "None recorded"}</div> })}
<div className="p-5 text-xs text-ink-dim">Concerns</div>{matches?.map((match) => { const analysis = match.latest_analysis_id ? analysisMap.get(match.latest_analysis_id) : null; return <div key={`concerns-${match.id}`} className="border-l border-border p-5 text-sm leading-[1.7] text-ink-dim">{(analysis?.potential_concerns as string[] | undefined)?.join(" · ") || "None recorded"}</div> })}
</div></div></div></main>;
}
