import Link from "next/link";
import { requireAuthenticatedUser } from "@/lib/supabase/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";
import CandidateNoteForm from "../note-form";
import EditCandidateProfile from "../edit-profile";

type Props = { params: Promise<{ candidateId: string }>; searchParams: Promise<{ jobId?: string }> };

export default async function CandidateProfilePage({ params, searchParams }: Props) {
  const user = await requireAuthenticatedUser(); const { candidateId } = await params; const { jobId } = await searchParams;
  const { data: candidate, error } = await supabaseAdmin.from("candidates").select("*").eq("id", candidateId).eq("user_id", user.id).single();
  if (error || !candidate) return <main className="min-h-screen bg-bg px-4 pb-20 pt-24 sm:px-6 sm:pt-28 lg:px-8"><div className="mx-auto max-w-wrap"><Link href="/dashboard/agents/recruitos/candidates" className="mb-8 inline-flex min-h-10 text-[13px] text-ink-dim">← Back to Candidates</Link><div className="rounded-xl border border-border p-7"><h1 className="font-display text-xl font-semibold text-ink">Candidate not found</h1><p className="mt-3 text-sm text-ink-dim">This candidate is not available in your workspace.</p></div></div></main>;
  const [{ data: resumes }, { data: matches }, { data: notes }, { data: activity }] = await Promise.all([
    supabaseAdmin.from("resumes").select("id, original_filename, storage_path, status, processing_status, created_at").eq("candidate_id", candidateId).eq("user_id", user.id).order("created_at", { ascending: false }),
    supabaseAdmin.from("candidate_job_matches").select("id, job_id, resume_id, latest_analysis_id, match_score, recommendation, recruiter_status, updated_at, jobs ( id, title )").eq("candidate_id", candidateId).eq("user_id", user.id).order("updated_at", { ascending: false }),
    supabaseAdmin.from("candidate_notes").select("id, content, created_at").eq("candidate_id", candidateId).eq("user_id", user.id).order("created_at", { ascending: false }),
    supabaseAdmin.from("candidate_activity").select("id, job_id, type, metadata, created_at, jobs ( title )").eq("candidate_id", candidateId).eq("user_id", user.id).order("created_at", { ascending: false }).limit(30),
  ]);
  const selectedMatch = matches?.find((match) => match.job_id === jobId) ?? matches?.[0]; let analysis: Record<string, unknown> | null = null;
  if (selectedMatch?.latest_analysis_id) { const { data } = await supabaseAdmin.from("resume_analyses").select("summary, match_score, recommendation, confidence_level, why_strong_match, matching_skills, missing_skills, potential_concerns, years_relevant_experience, reasoning").eq("id", selectedMatch.latest_analysis_id).eq("user_id", user.id).single(); analysis = data; }
  const experience = Array.isArray(candidate.experience) ? candidate.experience as Record<string, string | null>[] : []; const education = Array.isArray(candidate.education) ? candidate.education as Record<string, string | null>[] : []; const skills = Array.isArray(candidate.skills) ? candidate.skills as string[] : [];
  const card = "rounded-xl border border-border p-5 sm:p-7";

  return <main className="min-h-screen bg-bg px-4 pb-20 pt-24 sm:px-6 sm:pt-28 lg:px-8"><div className="mx-auto max-w-wrap">
    <Link href="/dashboard/agents/recruitos/candidates" className="mb-8 inline-flex min-h-10 items-center gap-2 rounded-md text-[13px] text-ink-dim transition-colors hover:text-ink">← Back to Candidates</Link>
    <header className="mb-9 border-b border-border pb-8 sm:mb-10 sm:pb-10"><p className="mb-4 font-mono text-[11px] tracking-[0.08em] text-accent">RECRUITOS / CANDIDATE</p><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><h1 className="break-words font-display text-[clamp(36px,5vw,64px)] font-semibold leading-[1.05] tracking-[-0.025em] text-ink">{candidate.full_name || "Unnamed candidate"}</h1><p className="mt-4 text-[15px] text-ink-dim">{candidate.headline || "Candidate profile"}{candidate.location ? ` · ${candidate.location}` : ""}</p></div><div className="flex flex-col items-start gap-3 sm:items-end">{candidate.email && <a href={`mailto:${candidate.email}`} className="max-w-full truncate text-sm text-accent">{candidate.email}</a>}<EditCandidateProfile candidate={{ id: candidate.id, full_name: candidate.full_name, email: candidate.email, phone: candidate.phone, location: candidate.location, headline: candidate.headline }} /></div></div></header>
    <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-4">
      <section className={card}><p className="font-mono text-[11px] tracking-[0.08em] text-accent">PROFILE</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><p className="text-xs text-ink-dim">Phone</p><p className="mt-2 text-sm text-ink">{candidate.phone || "Not provided"}</p></div><div><p className="text-xs text-ink-dim">Years of experience</p><p className="mt-2 text-sm text-ink">{candidate.years_experience ?? "Not available"}</p></div><div className="sm:col-span-2"><p className="text-xs text-ink-dim">Skills</p><div className="mt-3 flex flex-wrap gap-2">{skills.length ? skills.map((skill) => <span key={skill} className="rounded-md border border-border px-3 py-2 text-xs text-ink">{skill}</span>) : <span className="text-sm text-ink-dim">No structured skills extracted.</span>}</div></div></div></section>
      <section className={card}><p className="font-mono text-[11px] tracking-[0.08em] text-accent">EXPERIENCE</p><div className="mt-5 space-y-6">{experience.length ? experience.map((item, index) => <div key={`${item.company}-${index}`} className="border-l border-border pl-4 sm:pl-5"><h2 className="font-display text-lg font-semibold text-ink">{item.title || "Role"}</h2><p className="mt-1 text-sm text-ink-dim">{item.company || "Company"}{item.startDate || item.endDate ? ` · ${item.startDate ?? ""} – ${item.endDate ?? "Present"}` : ""}</p>{item.description && <p className="mt-3 text-sm leading-[1.7] text-ink-dim">{item.description}</p>}</div>) : <p className="text-sm text-ink-dim">No structured experience extracted.</p>}</div></section>
      <section className={card}><p className="font-mono text-[11px] tracking-[0.08em] text-accent">EDUCATION</p><div className="mt-5 space-y-4">{education.length ? education.map((item, index) => <div key={`${item.institution}-${index}`}><h2 className="font-display text-lg font-semibold text-ink">{item.degree || "Education"}{item.field ? ` · ${item.field}` : ""}</h2><p className="mt-1 text-sm text-ink-dim">{item.institution || "Institution"}</p></div>) : <p className="text-sm text-ink-dim">No structured education extracted.</p>}</div></section>
    </div>
    <aside className="space-y-4">
      <section className={card}><p className="font-mono text-[11px] tracking-[0.08em] text-accent">JOB MATCHES</p><div className="mt-5 space-y-3">{matches?.length ? matches.map((match) => { const job = Array.isArray(match.jobs) ? match.jobs[0] : match.jobs; return <Link key={match.id} href={`/dashboard/agents/recruitos/candidates/${candidateId}?jobId=${match.job_id}`} className={`block rounded-lg border p-4 transition-colors hover:border-accent/50 ${selectedMatch?.id === match.id ? "border-accent/50 bg-accent/[0.03]" : "border-border"}`}><div className="flex items-center justify-between gap-3"><span className="truncate text-sm font-medium text-ink">{job?.title || "Job"}</span><span className="font-mono text-sm text-accent">{match.match_score ?? "—"}</span></div><p className="mt-2 text-xs capitalize text-ink-dim">{match.recruiter_status} · {match.recommendation ?? "pending"}</p></Link> }) : <p className="text-sm text-ink-dim">No jobs associated yet.</p>}</div></section>
      {analysis && <section className={card}><p className="font-mono text-[11px] tracking-[0.08em] text-accent">AI INTELLIGENCE</p><p className="mt-4 font-display text-4xl font-semibold text-ink">{String(analysis.match_score)}/100</p><p className="mt-2 text-xs capitalize text-ink-dim">{String(analysis.recommendation)} · {String(analysis.confidence_level)} confidence</p><p className="mt-5 text-sm leading-[1.7] text-ink-dim">{String(analysis.summary)}</p><div className="mt-6 space-y-4"><div><p className="text-xs font-medium text-ink">Why this candidate matches</p><p className="mt-2 text-sm leading-[1.7] text-ink-dim">{String(analysis.why_strong_match)}</p></div><div><p className="text-xs font-medium text-ink">Strengths</p><div className="mt-2 flex flex-wrap gap-2">{(Array.isArray(analysis.matching_skills) ? analysis.matching_skills : []).map((skill) => <span key={String(skill)} className="rounded-md border border-border px-2.5 py-1.5 text-xs text-ink">{String(skill)}</span>)}</div></div><div><p className="text-xs font-medium text-ink">Gaps</p><div className="mt-2 space-y-1 text-sm text-ink-dim">{(Array.isArray(analysis.missing_skills) ? analysis.missing_skills : []).map((skill) => <p key={String(skill)}>• {String(skill)}</p>)}</div></div><div><p className="text-xs font-medium text-ink">Concerns</p><div className="mt-2 space-y-1 text-sm text-ink-dim">{(Array.isArray(analysis.potential_concerns) ? analysis.potential_concerns : []).map((item) => <p key={String(item)}>• {String(item)}</p>)}</div></div></div></section>}
      <section className={card}><p className="font-mono text-[11px] tracking-[0.08em] text-accent">RESUMES</p><div className="mt-5 space-y-3">{resumes?.length ? resumes.map((resume) => <div key={resume.id} className="flex items-center justify-between gap-3 rounded-lg border border-border p-4"><div className="min-w-0"><p className="truncate text-sm text-ink">{resume.original_filename}</p><p className="mt-1 text-xs capitalize text-ink-dim">{resume.processing_status || resume.status}</p></div><Link target="_blank" href={`/api/recruitos/resumes/${resume.id}/download`} className="min-h-9 shrink-0 inline-flex items-center text-xs text-accent">Open</Link></div>) : <p className="text-sm text-ink-dim">No resumes attached.</p>}</div></section>
    </aside></section>
    <section className={`mt-4 ${card}`}><p className="font-mono text-[11px] tracking-[0.08em] text-accent">PRIVATE NOTES</p><div className="mt-5"><CandidateNoteForm candidateId={candidateId} /></div><div className="mt-7 space-y-4">{notes?.map((note) => <div key={note.id} className="border-t border-border pt-4"><p className="text-sm leading-[1.7] text-ink">{note.content}</p><p className="mt-2 text-xs text-ink-dim">{new Date(note.created_at).toLocaleString()}</p></div>)}</div></section>
    <section className={`mt-4 ${card}`}><p className="font-mono text-[11px] tracking-[0.08em] text-accent">ACTIVITY</p><div className="mt-5 space-y-4">{activity?.length ? activity.map((item) => <div key={item.id} className="flex gap-4 border-l border-border pl-4"><div><p className="text-sm capitalize text-ink">{item.type.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-ink-dim">{new Date(item.created_at).toLocaleString()}</p></div></div>) : <p className="text-sm text-ink-dim">No activity recorded yet.</p>}</div></section>
  </div></main>;
}
