import type { ControlPlaneSnapshot } from "@/lib/control-plane/contracts";

export type ControlSection = "overview"|"products"|"agents"|"executions"|"health"|"learnings"|"improvements"|"evaluations"|"safety"|"approvals"|"versions"|"meta-agent";
const label = (value: string) => value.replaceAll("_", " ");
function Chip({ children, tone="neutral" }: { children: React.ReactNode; tone?: "neutral"|"good"|"warn"|"bad"|"blue" }) { return <span className={`cp-chip cp-chip-${tone}`}>{children}</span>; }
function Header({ eyebrow, title, copy, tag }: { eyebrow:string;title:string;copy:string;tag?:string }) { return <div className="cp-page-heading"><div><span className="cp-kicker">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{tag&&<Chip tone="blue">{tag}</Chip>}</div>; }
function Stat({ label: name, value, detail, tone="neutral" }: {label:string;value:string;detail:string;tone?:"neutral"|"good"|"warn"|"bad"}) { return <article className="cp-stat"><span>{name}</span><strong className={`cp-value-${tone}`}>{value}</strong><p>{detail}</p></article>; }
function RefList({ ids }: { ids: readonly string[] }) { return <div className="cp-refs">{ids.map(id=><code key={id}>{id}</code>)}</div>; }

export function ControlPlaneView({ snapshot: s, section }: { snapshot: ControlPlaneSnapshot; section: ControlSection }) {
  if(section==="overview") return <main className="cp-main"><Header eyebrow="System overview" title="Command Center" copy="The few signals that need founder attention, grounded in authoritative records." tag={s.sourceMode}/><div className="cp-stats"><Stat label="System health" value={label(s.health.state)} detail={`${Math.round((s.health.successRate??0)*100)}% verified success`} tone={s.health.state==="healthy"?"good":"warn"}/><Stat label="Pending decisions" value={String(s.approvals.filter(x=>x.status==="pending").length)} detail="Exact action-bound approvals" tone="warn"/><Stat label="Active products" value={String(s.products.length)} detail="Immutable product snapshots"/><Stat label="Safety findings" value={String(s.health.openSafetyFindings)} detail="Guardian advisory findings" tone={s.health.openSafetyFindings?"warn":"good"}/></div><div className="cp-grid cp-grid-2"><section className="cp-panel"><div className="cp-panel-head"><div><span className="cp-kicker">Attention queue</span><h2>Founder decisions</h2></div></div>{s.approvals.map(a=><article className="cp-row" key={a.approvalId}><div><Chip tone="warn">{a.risk} risk</Chip><h3>{a.actionType}</h3><p>{a.payloadSummary}</p></div><code>{a.approvalId}</code></article>)}</section><section className="cp-panel"><div className="cp-panel-head"><div><span className="cp-kicker">Recent activity</span><h2>Important events</h2></div></div>{s.recentEvents.map(e=><article className="cp-timeline" key={e.eventId}><span className={`cp-event cp-event-${e.severity}`}/><div><p>{e.summary}</p><code>{e.reference.kind}:{e.reference.id}</code></div><time>{new Date(e.occurredAt).toLocaleTimeString("en",{hour:"2-digit",minute:"2-digit"})}</time></article>)}</section></div><section className="cp-panel cp-system-map"><div className="cp-panel-head"><div><span className="cp-kicker">Authority map</span><h2>How OperationOS governs change</h2></div><Chip tone="good">Runtime enforced</Chip></div><div className="cp-map">{["Products","Manager","Specialists","Runtime","Observations","Optimizer","Evaluation","Risk Gate"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div><p>Safety Guardian observes relevant boundaries. The human operator governs consequential transitions.</p></section></main>;
  if(section==="products") return <main className="cp-main"><Header eyebrow="Product registry" title="Products" copy="Registered product state resolved from immutable snapshots."/>{s.products.map(p=><section className="cp-panel cp-product" key={p.productKey}><div className="cp-panel-head"><div><Chip tone="good">Registered</Chip><h2>{p.name}</h2><code>{p.productKey} · {p.productVersionId}</code></div><code>{p.snapshotId}</code></div><div className="cp-mini-grid"><div><span>Features</span><strong>{p.featureCount}</strong></div><div><span>Recent executions</span><strong>{p.recentExecutionCount}</strong></div><div><span>Capabilities</span><strong>{p.capabilityKeys.length}</strong></div><div><span>Evaluators</span><strong>{p.evaluatorKeys.length}</strong></div></div><div className="cp-detail-grid"><div><h3>Capabilities</h3><RefList ids={p.capabilityKeys}/></div><div><h3>Signals</h3><RefList ids={p.signalKeys}/></div><div><h3>Workflows</h3><RefList ids={p.workflowKeys}/></div><div><h3>Evaluators</h3><RefList ids={p.evaluatorKeys}/></div></div></section>)}</main>;
  if(section==="agents") return <main className="cp-main"><Header eyebrow="Runtime registry" title="Agents" copy="Roles, versions, and explicit authority boundaries—never hidden reasoning."/><div className="cp-card-grid">{s.agents.map(a=><article className="cp-panel cp-agent" key={a.agentKey}><div className="cp-panel-head"><Chip tone={a.status==="active"?"good":"warn"}>{a.status}</Chip><code>{a.versionId}</code></div><span className="cp-kicker">{a.role}</span><h2>{label(a.agentKey)}</h2><p>{a.boundarySummary}</p><div className="cp-agent-foot"><RefList ids={a.capabilityKeys}/><span>{a.recentExecutionCount} recent</span></div></article>)}</div></main>;
  if(section==="executions") return <main className="cp-main"><Header eyebrow="Runtime activity" title="Executions" copy="Sanitized goals, assignments, verification, retries, and trace health."/><section className="cp-panel cp-table-wrap"><table className="cp-table"><thead><tr><th>Execution</th><th>Goal</th><th>State</th><th>Agents</th><th>Recovery</th><th>Verification</th><th>Trace</th></tr></thead><tbody>{s.executions.map(x=><tr key={x.executionId}><td><code>{x.executionId}</code><small>{x.productKey}</small></td><td>{x.goalSummary}{x.sanitizedError&&<small className="cp-danger">{x.sanitizedError}</small>}</td><td><Chip tone={x.state==="succeeded"?"good":"bad"}>{x.state}</Chip></td><td>{x.agentKeys.length}</td><td>{x.retries}R · {x.replans}P</td><td><Chip tone={x.verificationStatus==="passed"?"good":"bad"}>{x.verificationStatus}</Chip></td><td>{x.traceEventCount} events</td></tr>)}</tbody></table></section></main>;
  if(section==="health") return <main className="cp-main"><Header eyebrow="Operational integrity" title="System Health" copy="Measured reliability signals; no vanity metrics."/><div className="cp-stats"><Stat label="Verified success" value={`${Math.round((s.health.successRate??0)*100)}%`} detail="Across bounded fixture window" tone="good"/><Stat label="Verification failures" value={String(s.health.verificationFailures)} detail="Required evidence missing" tone="warn"/><Stat label="Retries / replans" value={`${s.health.retries} / ${s.health.replans}`} detail="Preserved attempts and plans"/><Stat label="Trace persistence" value={s.health.traceStoreHealthy?"Healthy":"Degraded"} detail="Append-only event store" tone={s.health.traceStoreHealthy?"good":"bad"}/></div><section className="cp-panel"><div className="cp-panel-head"><h2>System posture</h2><Chip tone={s.health.providerFailures?"bad":"good"}>{s.health.providerFailures} provider failures</Chip></div><p className="cp-copy">System health is derived from execution outcomes, verification, recovery, safety, and persistence integrity. The Control Plane does not change those source records.</p></section></main>;
  return <main className="cp-main"><Header eyebrow="Control Plane" title={label(section)} copy="This operational projection is added in the next verified milestone."/></main>;
}
