import Link from "next/link";
import { requireAuthenticatedUser } from "@/lib/supabase/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";
import RecruiterSummary from "./recruiter-summary";

export default async function RecruitOSPage() {
  const user = await requireAuthenticatedUser();
  const [{ data: jobs }, { count: candidates }, { count: reviewCount }, { count: interviews }, { data: topCandidates }] = await Promise.all([
    supabaseAdmin.from("jobs").select("id, title, status, lifecycle_status, created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(5),
    supabaseAdmin.from("candidates").select("id", { count: "exact", head: true }).eq("user_id", user.id),
    supabaseAdmin.from("candidate_job_matches").select("id", { count: "exact", head: true }).eq("user_id", user.id).in("recruiter_status", ["new", "reviewing"]),
    supabaseAdmin.from("candidate_job_matches").select("id", { count: "exact", head: true }).eq("user_id", user.id).eq("recruiter_status", "interview"),
    supabaseAdmin.from("candidate_job_matches").select("id, candidate_id, job_id, match_score, candidates ( full_name, email ), jobs ( title )").eq("user_id", user.id).order("match_score", { ascending: false, nullsFirst: false }).limit(5),
  ]);
  const hasJobs = Boolean(jobs?.length);

  return <main className="min-h-screen bg-bg px-5 pb-20 pt-28 sm:px-8"><div className="mx-auto max-w-wrap">
    <Link href="/dashboard" className="mb-10 inline-flex items-center gap-2 text-[13px] text-ink-dim">← Back to agents</Link>
    <div className="mb-10 border-b border-border pb-10"><div className="mb-5 flex items-center gap-3"><span className="font-mono text-[11px] tracking-[0.08em] text-accent">EMPLOYEE 001</span><span className="rounded-full border border-accent/20 bg-accent/[0.06] px-2.5 py-1 font-mono text-[10px] tracking-[0.05em] text-accent">ACTIVE</span></div><h1 className="font-display text-[clamp(36px,5vw,64px)] font-semibold leading-[1.05] tracking-[-0.025em] text-ink">RecruitOS</h1><p className="mt-4 max-w-[720px] text-[15px] leading-[1.7] text-ink-dim">Your AI recruiting employee. Identify strong candidates, understand fit, and keep control over every hiring decision.</p></div>

    {!hasJobs && <section className="mb-10 rounded-xl border border-accent/30 bg-accent/[0.03] p-6 sm:p-8"><p className="font-mono text-[11px] tracking-[0.08em] text-accent">WELCOME TO RECRUITOS</p><h2 className="mt-3 font-display text-2xl font-semibold text-ink">Build your first hiring pipeline.</h2><p className="mt-3 max-w-[700px] text-sm leading-[1.7] text-ink-dim">Create a job, upload one or more resumes, and RecruitOS will turn them into persistent candidate profiles with job-specific AI match intelligence.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/dashboard/agents/recruitos/jobs/new" className="rounded-lg bg-accent px-5 py-3 text-sm font-medium text-bg">Create your first job</Link><Link href="/dashboard/agents/recruitos/candidates" className="rounded-lg border border-border px-5 py-3 text-sm text-ink">Explore candidates</Link></div></section>}

    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border border-border p-6"><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-ink-dim">Active jobs</p><p className="mt-3 font-display text-3xl font-semibold text-ink">{jobs?.filter((job) => (job.lifecycle_status ?? job.status) === "open").length ?? 0}</p></div><div className="rounded-xl border border-border p-6"><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-ink-dim">Candidates</p><p className="mt-3 font-display text-3xl font-semibold text-ink">{candidates ?? 0}</p></div><div className="rounded-xl border border-border p-6"><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-ink-dim">Needs review</p><p className="mt-3 font-display text-3xl font-semibold text-ink">{reviewCount ?? 0}</p></div><div className="rounded-xl border border-border p-6"><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-ink-dim">Interviews</p><p className="mt-3 font-display text-3xl font-semibold text-ink">{interviews ?? 0}</p></div></section>
    <RecruiterSummary />
    <section className="mt-10 grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-border p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="font-mono text-[11px] tracking-[0.08em] text-accent">TOP CANDIDATES</p><h2 className="mt-3 font-display text-2xl font-semibold text-ink">Highest match scores</h2></div><Link href="/dashboard/agents/recruitos/candidates" className="text-sm text-accent">View all →</Link></div><div className="mt-6 space-y-3">{topCandidates?.length ? topCandidates.map((match) => { const candidate = Array.isArray(match.candidates) ? match.candidates[0] : match.candidates; const job = Array.isArray(match.jobs) ? match.jobs[0] : match.jobs; return <Link key={match.id} href={`/dashboard/agents/recruitos/candidates/${match.candidate_id}?jobId=${match.job_id}`} className="flex items-center justify-between gap-4 rounded-lg border border-border p-4"><div className="min-w-0"><p className="truncate text-sm font-medium text-ink">{candidate?.full_name || candidate?.email || "Unnamed candidate"}</p><p className="mt-1 truncate text-xs text-ink-dim">{job?.title || "Job"}</p></div><span className="font-mono text-lg text-accent">{match.match_score ?? "—"}</span></Link> }) : <p className="text-sm text-ink-dim">Analyze resumes to start ranking candidates.</p>}</div></div>
      <div className="rounded-xl border border-border p-6 sm:p-8"><p className="font-mono text-[11px] tracking-[0.08em] text-accent">RECENT JOBS</p><h2 className="mt-3 font-display text-2xl font-semibold text-ink">Hiring workspace</h2><div className="mt-6 space-y-3">{jobs?.length ? jobs.map((job) => <Link key={job.id} href={`/dashboard/agents/recruitos/jobs/${job.id}`} className="flex items-center justify-between gap-4 rounded-lg border border-border p-4"><div className="min-w-0"><p className="truncate text-sm font-medium text-ink">{job.title}</p><p className="mt-1 text-xs capitalize text-ink-dim">{job.lifecycle_status ?? job.status}</p></div><span className="text-sm text-accent">Open →</span></Link>) : <p className="text-sm text-ink-dim">No jobs created yet.</p>}<Link href="/dashboard/agents/recruitos/jobs/new" className="inline-flex rounded-lg bg-accent px-5 py-3 text-sm font-medium text-bg">Create a job</Link></div></div></section>
    <section className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3"><Link href="/dashboard/agents/recruitos/analyze" className="group rounded-xl border border-border p-6 hover:border-accent/40"><p className="font-mono text-sm text-accent">AI</p><h2 className="mt-8 font-display text-lg font-semibold text-ink">Analyze resumes</h2><p className="mt-2 text-sm leading-[1.6] text-ink-dim">Upload and analyze a candidate against a job.</p></Link><Link href="/dashboard/agents/recruitos/candidates" className="group rounded-xl border border-border p-6 hover:border-accent/40"><p className="font-mono text-sm text-accent">CV</p><h2 className="mt-8 font-display text-lg font-semibold text-ink">Candidates</h2><p className="mt-2 text-sm leading-[1.6] text-ink-dim">Search and manage your candidate pool.</p></Link><Link href="/dashboard/agents/recruitos/jobs" className="group rounded-xl border border-border p-6 hover:border-accent/40"><p className="font-mono text-sm text-accent">JOB</p><h2 className="mt-8 font-display text-lg font-semibold text-ink">Jobs</h2><p className="mt-2 text-sm leading-[1.6] text-ink-dim">Manage roles and their hiring pipelines.</p></Link></section>
  </div></main>;
}
