import Link from "next/link";
import { requireAuthenticatedUser } from "@/lib/supabase/auth";
import { supabaseAdmin } from "@/lib/supabase/admin";
import RecruiterSummary from "./recruiter-summary";

export default async function RecruitOSPage() {
  const user = await requireAuthenticatedUser();
  const [{ data: jobs }, { count: candidates }, { count: reviewCount }, { count: interviews }, { data: topCandidates }] = await Promise.all([
    supabaseAdmin.from("jobs").select("id, title, status, lifecycle_status, created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(5),
    supabaseAdmin.from("candidates").select("id", { count: "exact", head: true }).eq("user_id", user.id),
    supabaseAdmin.from("candidate_job_matches").select("id", { count: "exact", head: true }).eq("user_id", user.id).in("recruiter_status", ["new", "reviewing"]),
    supabaseAdmin.from("candidate_job_matches").select("id", { count: "exact", head: true }).eq("user_id", user.id).eq("recruiter_status", "interview"),
    supabaseAdmin.from("candidate_job_matches").select("id, candidate_id, job_id, match_score, candidates ( full_name, email ), jobs ( title )").eq("user_id", user.id).order("match_score", { ascending: false, nullsFirst: false }).limit(5),
  ]);
  const hasJobs = Boolean(jobs?.length);

  return <main className="min-h-screen bg-bg px-4 pb-20 pt-24 sm:px-6 sm:pt-28 lg:px-8"><div className="mx-auto max-w-wrap">
    <Link href="/dashboard" className="mb-8 inline-flex min-h-10 items-center gap-2 rounded-md text-[13px] text-ink-dim transition-colors hover:text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent">← Back to agents</Link>
    <div className="mb-9 border-b border-border pb-8 sm:mb-10 sm:pb-10"><div className="mb-4 flex flex-wrap items-center gap-3"><span className="font-mono text-[11px] tracking-[0.08em] text-accent">EMPLOYEE 001</span><span className="rounded-full border border-accent/20 bg-accent/[0.06] px-2.5 py-1 font-mono text-[10px] tracking-[0.05em] text-accent">ACTIVE</span></div><h1 className="font-display text-[clamp(36px,5vw,64px)] font-semibold leading-[1.05] tracking-[-0.025em] text-ink">RecruitOS</h1><p className="mt-4 max-w-[720px] text-[15px] leading-[1.7] text-ink-dim">Your AI recruiting employee. Identify strong candidates, understand fit, and keep control over every hiring decision.</p></div>

    {!hasJobs && <section className="mb-8 rounded-xl border border-accent/30 bg-accent/[0.03] p-5 sm:mb-10 sm:p-8"><p className="font-mono text-[11px] tracking-[0.08em] text-accent">WELCOME TO RECRUITOS</p><h2 className="mt-3 font-display text-2xl font-semibold text-ink">Build your first hiring pipeline.</h2><p className="mt-3 max-w-[700px] text-sm leading-[1.7] text-ink-dim">Create a job, upload one or more resumes, and RecruitOS will turn them into persistent candidate profiles with job-specific AI match intelligence.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/dashboard/agents/recruitos/jobs/new" className="inline-flex min-h-11 items-center justify-center rounded-lg bg-accent px-5 py-3 text-sm font-medium text-bg transition-opacity hover:opacity-90">Create your first job</Link><Link href="/dashboard/agents/recruitos/candidates" className="inline-flex min-h-11 items-center justify-center rounded-lg border border-border px-5 py-3 text-sm text-ink transition-colors hover:border-accent hover:text-accent">Explore candidates</Link></div></section>}

    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{ label: "Active jobs", value: jobs?.filter((job) => (job.lifecycle_status ?? job.status) === "open").length ?? 0 }, { label: "Candidates", value: candidates ?? 0 }, { label: "Needs review", value: reviewCount ?? 0 }, { label: "Interviews", value: interviews ?? 0 }].map((metric) => <div key={metric.label} className="rounded-xl border border-border bg-surface/[0.35] p-5 sm:p-6"><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-ink-dim">{metric.label}</p><p className="mt-3 font-display text-3xl font-semibold text-ink">{metric.value}</p></div>)}</section>
    <RecruiterSummary />
    <section className="mt-8 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-border p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[11px] tracking-[0.08em] text-accent">TOP CANDIDATES</p><h2 className="mt-3 font-display text-2xl font-semibold text-ink">Highest match scores</h2></div><Link href="/dashboard/agents/recruitos/candidates" className="shrink-0 text-sm text-accent">View all →</Link></div><div className="mt-6 space-y-3">{topCandidates?.length ? topCandidates.map((match) => { const candidate = Array.isArray(match.candidates) ? match.candidates[0] : match.candidates; const job = Array.isArray(match.jobs) ? match.jobs[0] : match.jobs; return <Link key={match.id} href={`/dashboard/agents/recruitos/candidates/${match.candidate_id}?jobId=${match.job_id}`} className="flex min-h-16 items-center justify-between gap-4 rounded-lg border border-border p-4 transition-colors hover:border-accent/40 hover:bg-white/[0.02]"><div className="min-w-0"><p className="truncate text-sm font-medium text-ink">{candidate?.full_name || candidate?.email || "Unnamed candidate"}</p><p className="mt-1 truncate text-xs text-ink-dim">{job?.title || "Job"}</p></div><span className="font-mono text-lg text-accent">{match.match_score ?? "—"}</span></Link> }) : <p className="text-sm text-ink-dim">Analyze resumes to start ranking candidates.</p>}</div></div>
      <div className="rounded-xl border border-border p-5 sm:p-7"><p className="font-mono text-[11px] tracking-[0.08em] text-accent">RECENT JOBS</p><h2 className="mt-3 font-display text-2xl font-semibold text-ink">Hiring workspace</h2><div className="mt-6 space-y-3">{jobs?.length ? jobs.map((job) => <Link key={job.id} href={`/dashboard/agents/recruitos/jobs/${job.id}`} className="flex min-h-16 items-center justify-between gap-4 rounded-lg border border-border p-4 transition-colors hover:border-accent/40 hover:bg-white/[0.02]"><div className="min-w-0"><p className="truncate text-sm font-medium text-ink">{job.title}</p><p className="mt-1 text-xs capitalize text-ink-dim">{job.lifecycle_status ?? job.status}</p></div><span className="shrink-0 text-sm text-accent">Open →</span></Link>) : <p className="text-sm text-ink-dim">No jobs created yet.</p>}<Link href="/dashboard/agents/recruitos/jobs/new" className="inline-flex min-h-11 items-center rounded-lg bg-accent px-5 py-3 text-sm font-medium text-bg transition-opacity hover:opacity-90">Create a job</Link></div></div></section>
    <section className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-3">{[{ href: "/dashboard/agents/recruitos/analyze", code: "AI", title: "Analyze resumes", body: "Upload and analyze a candidate against a job." }, { href: "/dashboard/agents/recruitos/candidates", code: "CV", title: "Candidates", body: "Search and manage your candidate pool." }, { href: "/dashboard/agents/recruitos/jobs", code: "JOB", title: "Jobs", body: "Manage roles and their hiring pipelines." }].map((item) => <Link key={item.href} href={item.href} className="group rounded-xl border border-border p-5 transition-colors hover:border-accent/40 hover:bg-white/[0.02] sm:p-6"><p className="font-mono text-sm text-accent">{item.code}</p><h2 className="mt-7 font-display text-lg font-semibold text-ink">{item.title}</h2><p className="mt-2 text-sm leading-[1.6] text-ink-dim">{item.body}</p></Link>)}</section>
  </div></main>;
}
