"use client";

import { useState, useTransition } from "react";
import { updateCandidate } from "@/app/actions/update-candidate";

export default function EditCandidateProfile({ candidate }: { candidate: { id: string; full_name: string | null; email: string | null; phone: string | null; location: string | null; headline: string | null } }) {
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ fullName: candidate.full_name ?? "", email: candidate.email ?? "", phone: candidate.phone ?? "", location: candidate.location ?? "", headline: candidate.headline ?? "" });
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  function save() { setError(null); startTransition(async () => { const result = await updateCandidate(candidate.id, form); if (!result.success) setError(result.error ?? "Could not update candidate."); else { setOpen(false); window.location.reload(); } }); }
  return <div>{!open ? <button type="button" onClick={() => setOpen(true)} className="rounded-lg border border-border px-4 py-2.5 text-xs font-medium text-ink hover:border-accent hover:text-accent">Edit profile</button> : <div className="mt-5 rounded-lg border border-border p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><input value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} placeholder="Full name" className="rounded-lg border border-border bg-transparent px-4 py-3 text-sm text-ink outline-none focus:border-accent" /><input value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="Email" className="rounded-lg border border-border bg-transparent px-4 py-3 text-sm text-ink outline-none focus:border-accent" /><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="Phone" className="rounded-lg border border-border bg-transparent px-4 py-3 text-sm text-ink outline-none focus:border-accent" /><input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} placeholder="Location" className="rounded-lg border border-border bg-transparent px-4 py-3 text-sm text-ink outline-none focus:border-accent" /><input value={form.headline} onChange={(e) => setForm({ ...form, headline: e.target.value })} placeholder="Current role / headline" className="rounded-lg border border-border bg-transparent px-4 py-3 text-sm text-ink outline-none focus:border-accent sm:col-span-2" /></div><div className="mt-4 flex gap-2"><button type="button" onClick={save} disabled={pending} className="rounded-lg bg-accent px-4 py-2.5 text-xs font-medium text-bg">{pending ? "Saving..." : "Save profile"}</button><button type="button" onClick={() => setOpen(false)} className="rounded-lg border border-border px-4 py-2.5 text-xs text-ink">Cancel</button></div>{error && <p className="mt-3 text-xs text-red-400">{error}</p>}</div>}</div>;
}
